.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH checksum 1  "checksum " 
.SH NAME
checksum \- Verifies checksums
.SH SYNOPSIS
\fBchecksum\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-o\fR|\fB\-\-output\fR] [\fB\-\-overwrite\fR] <\fIinput\fR> 
.SH DESCRIPTION
Verifies WARC record checksums.
.PP
This processes each WARC record for a \*(AqWARC\-Block\-Digest\*(Aq field. If the record includes this field, the checksum is computed for the record\*(Aqs block.
.PP
The output is formatted as the record\*(Aqs ID, a space, and one of \*(Aqok\*(Aq, \*(Aqfail\*(Aq, or \*(Aqskip\*(Aq.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-o\fR, \fB\-\-output\fR [default: \-]
Path to output file
.TP
\fB\-\-overwrite\fR [default: false]
Allow overwriting existing files
.TP
<\fIinput\fR>
Path to WARC file
