.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH address 1  "address " 
.SH NAME
address \- Lookup IP addresses for a hostname
.SH SYNOPSIS
\fBaddress\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIhostname\fR> 
.SH DESCRIPTION
Lookup IP addresses for a hostname
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fIhostname\fR>
Target hostname to query
