[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "3.2", features = ["color", "suggestions", "cargo", "unicode", "wrap_help"] }
regex = "1.5"
serde_json = "1.0"
