name: Rust build release binaries

on:
  workflow_dispatch:
  push: tags

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        target:
          - os: windows-2022
            triple: x86_64-pc-windows-msvc
            cross: false
          - os: macos-10.15
            triple: x86_64-apple-darwin
            cross: false
          - os: ubuntu-20.04
            triple: x86_64-unknown-linux-gnu
            cross: false
          - os: ubuntu-20.04
            triple: armv7-unknown-linux-gnueabihf
            cross: true

    runs-on: ${{ matrix.target.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
    - uses: Swatinem/rust-cache@v1

    - name: Build release binaries
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --release --target ${{ matrix.target.triple }}
        use_cross: ${{ matrix.target.cross }}

    - name: Generate release docs
      run: cargo xtask gen-copyright-file

    - name: Package app
      run: cargo xtask package-app --target-triple ${{ matrix.target.triple }}

    - uses: actions/upload-artifact@v3
      with:
        name: package_app-${{ matrix.target.triple }}
        path: target/xtask/zip/*
